<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net472;net48;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.0</Version>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <PackageId>$(AssemblyName)</PackageId>
    <Authors>ema</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <RepositoryUrl>https://github.com/emako/LiteObservableEvents</RepositoryUrl>
    <PackageProjectUrl>https://github.com/emako/LiteObservableEvents</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>LiteObservableEvents MVVM</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Description>XXX</Description>
    <PackageIcon>Logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IncludeSymbols>true</IncludeSymbols>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\Logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>
</Project>